(function (root) {
	const VERT = [
		'attribute vec3 aPosition;',
		'attribute vec2 aTexCoord;',
		'uniform mat4 uProjectionMatrix;',
		'uniform mat4 uModelViewMatrix;',
		'varying vec2 vTexCoord;',
		'void main() {',
		'  vTexCoord = aTexCoord;',
		'  gl_Position = uProjectionMatrix * uModelViewMatrix * vec4(aPosition, 1.0);',
		'}'
	].join('\n');

	const FILTER = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_time;',
		'uniform sampler2D u_input;',
		'',
		'vec2 uv() {',
		'  return vTexCoord;',
		'}',
		'',
		'vec4 src() {',
		'  return texture2D(u_input, uv());',
		'}'
	].join('\n');

	const TILE_FN = [
		'vec2 tileUv(vec2 st, float mode) {',
		'  if (mode < 0.5) return clamp(st, 0.0, 1.0);',
		'  if (mode < 1.5) return fract(st);',
		'  return abs(fract(st * 0.5 + 0.5) * 2.0 - 1.0);',
		'}'
	].join('\n');

	const BLEND_BODY = [
		'vec3 blendWith(vec3 gen) {',
		'  if (u_hasInput < 0.5) return gen;',
		'  vec3 prev = texture2D(u_input, vTexCoord).rgb;',
		'  if (u_blendMode < 0.5) return gen;',
		'  if (u_blendMode < 1.5) return min(prev + gen, 1.0);',
		'  if (u_blendMode < 2.5) return prev * gen;',
		'  if (u_blendMode < 3.5) return vec3(1.0) - (vec3(1.0) - prev) * (vec3(1.0) - gen);',
		'  if (u_blendMode < 4.5) return abs(prev - gen);',
		'  if (u_blendMode < 5.5) {',
		'    vec3 low = 2.0 * prev * gen;',
		'    vec3 high = vec3(1.0) - 2.0 * (vec3(1.0) - prev) * (vec3(1.0) - gen);',
		'    return mix(low, high, step(0.5, prev));',
		'  }',
		'  if (u_blendMode < 6.5) return max(prev - gen, 0.0);',
		'  if (u_blendMode < 7.5) return max(prev, gen);',
		'  return min(prev, gen);',
		'}'
	].join('\n');

	const BLEND_FN = [
		'uniform sampler2D u_input;',
		'uniform float u_hasInput;',
		'uniform float u_blendMode;',
		'',
		BLEND_BODY
	].join('\n');

	const LINES = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_fuzzyness;',
		'uniform float u_amount;',
		'uniform float u_width;',
		'uniform float u_rotation;',
		'uniform float u_position;',
		'uniform vec3 u_color;',
		BLEND_FN,
		'',
		'void main() {',
		'  vec2 p = vTexCoord * 2.0 - 1.0;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_rotation * 0.017453292;',
		'  vec2 dir = vec2(sin(ang), cos(ang));',
		'  float n = u_amount;',
		'  float coord = dot(p, dir) * 0.5 + 0.5 + u_position;',
		'  float g = abs(fract(coord * max(n, 1.0)) - 0.5) * 2.0;',
		'  float halfW = clamp(u_width, 0.0, 1.0);',
		'  float fuzz = mix(0.003, 0.5, clamp(u_fuzzyness, 0.0, 1.0));',
		'  float v = (1.0 - smoothstep(halfW, halfW + fuzz, g)) * step(0.5, n);',
		'  gl_FragColor = vec4(blendWith(u_color * v), 1.0);',
		'}'
	].join('\n');

	const NOISE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_time;',
		'uniform float u_scale;',
		'uniform vec3 u_translate;',
		'uniform vec3 u_speed;',
		'uniform float u_amplitude;',
		'uniform float u_offset;',
		'uniform float u_octaves;',
		'uniform float u_contrastPow;',
		'uniform float u_use3d;',
		BLEND_FN,
		'',
		'vec4 hash4(vec4 x, vec4 y, vec4 z) {',
		'  x = fract(x * 0.1031);',
		'  y = fract(y * 0.1031);',
		'  z = fract(z * 0.1031);',
		'  vec4 d = x * (z + 33.33) + y * (y + 33.33) + z * (x + 33.33);',
		'  x += d;',
		'  y += d;',
		'  z += d;',
		'  return fract((x + y) * z);',
		'}',
		'',
		'float valueNoise(vec3 p) {',
		'  vec3 i = floor(p);',
		'  vec3 f = fract(p);',
		'  vec3 u = f * f * (3.0 - 2.0 * f);',
		'  vec4 ix = i.x + vec4(0.0, 1.0, 0.0, 1.0);',
		'  vec4 iy = i.y + vec4(0.0, 0.0, 1.0, 1.0);',
		'  vec4 h0 = hash4(ix, iy, vec4(i.z));',
		'  float n0 = mix(mix(h0.x, h0.y, u.x), mix(h0.z, h0.w, u.x), u.y);',
		'  if (u_use3d < 0.5) return n0;',
		'  vec4 h1 = hash4(ix, iy, vec4(i.z + 1.0));',
		'  float n1 = mix(mix(h1.x, h1.y, u.x), mix(h1.z, h1.w, u.x), u.y);',
		'  return mix(n0, n1, u.z);',
		'}',
		'',
		'float fbm(vec3 p) {',
		'  float amp = 0.5;',
		'  float sum = valueNoise(p) * amp;',
		'  float norm = amp;',
		'  if (u_octaves < 1.5) return sum / max(norm, 0.001);',
		'  p *= 2.03;',
		'  amp *= 0.5;',
		'  sum += valueNoise(p) * amp;',
		'  norm += amp;',
		'  if (u_octaves < 2.5) return sum / max(norm, 0.001);',
		'  p *= 2.03;',
		'  amp *= 0.5;',
		'  sum += valueNoise(p) * amp;',
		'  norm += amp;',
		'  if (u_octaves < 3.5) return sum / max(norm, 0.001);',
		'  p *= 2.03;',
		'  amp *= 0.5;',
		'  sum += valueNoise(p) * amp;',
		'  norm += amp;',
		'  if (u_octaves < 4.5) return sum / max(norm, 0.001);',
		'  p *= 2.03;',
		'  amp *= 0.5;',
		'  sum += valueNoise(p) * amp;',
		'  norm += amp;',
		'  if (u_octaves < 5.5) return sum / max(norm, 0.001);',
		'  p *= 2.03;',
		'  amp *= 0.5;',
		'  sum += valueNoise(p) * amp;',
		'  norm += amp;',
		'  return sum / max(norm, 0.001);',
		'}',
		'',
		'void main() {',
		'  vec2 p = vTexCoord;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  vec3 q = vec3(p * u_scale, 0.0) + u_translate + u_speed * u_time;',
		'  q.xy += 0.35 * vec2(valueNoise(q), valueNoise(q.yxz));',
		'  float v = fbm(q);',
		'  if (u_contrastPow < 0.98 || u_contrastPow > 1.02) {',
		'    v = pow(max(v, 0.0), u_contrastPow);',
		'  }',
		'  v = clamp(v * u_amplitude + u_offset, 0.0, 1.0);',
		'  gl_FragColor = vec4(blendWith(vec3(v)), 1.0);',
		'}'
	].join('\n');

	const CAMERA = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform sampler2D u_video;',
		BLEND_FN,
		'',
		'void main() {',
		'  vec3 cam = texture2D(u_video, vTexCoord).rgb;',
		'  gl_FragColor = vec4(blendWith(cam), 1.0);',
		'}'
	].join('\n');

	const KALEIDOSCOPE = [
		FILTER,
		TILE_FN,
		'uniform float u_segments;',
		'uniform float u_angle;',
		'uniform float u_zoom;',
		'uniform float u_offsetX;',
		'uniform float u_offsetY;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 uv = vTexCoord - 0.5;',
		'  uv.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  uv -= vec2(u_offsetX, u_offsetY) - 0.5;',
		'  float ang = u_angle * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  uv = vec2(c * uv.x - s * uv.y, s * uv.x + c * uv.y);',
		'  float r = length(uv);',
		'  float a = atan(uv.y, uv.x);',
		'  float slices = max(u_segments, 2.0);',
		'  float ta = 3.14159265 / slices;',
		'  a = mod(a, ta * 2.0);',
		'  a = abs(a - ta);',
		'  vec2 st = vec2(cos(a), sin(a)) * r / max(u_zoom, 0.05);',
		'  st.x /= u_resolution.x / max(u_resolution.y, 1.0);',
		'  st += 0.5;',
		'  gl_FragColor = texture2D(u_input, tileUv(st, u_tile));',
		'}'
	].join('\n');

	const WARP = [
		FILTER,
		TILE_FN,
		'uniform float u_amount;',
		'uniform float u_frequency;',
		'uniform float u_speed;',
		'uniform float u_detail;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  float t = u_time * u_speed;',
		'  vec2 q = st;',
		'  q += u_amount * 0.22 * vec2(',
		'    sin(st.y * u_frequency + t),',
		'    cos(st.x * u_frequency * 0.91 - t)',
		'  );',
		'  q += u_amount * u_detail * 0.12 * vec2(',
		'    sin(q.y * u_frequency * 2.15 - t * 1.3),',
		'    cos(q.x * u_frequency * 1.87 + t * 1.1)',
		'  );',
		'  gl_FragColor = texture2D(u_input, tileUv(q, u_tile));',
		'}'
	].join('\n');

	const HSV_FN = [
		'vec3 rgb2hsv(vec3 c) {',
		'  vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);',
		'  vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));',
		'  vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));',
		'  float d = q.x - min(q.w, q.y);',
		'  float e = 1.0e-10;',
		'  return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);',
		'}',
		'',
		'vec3 hsv2rgb(vec3 c) {',
		'  vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);',
		'  vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);',
		'  return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);',
		'}'
	].join('\n');

	const LOOKUP = [
		FILTER,
		'uniform sampler2D u_lut;',
		'uniform float u_hue;',
		'uniform float u_saturation;',
		'uniform float u_exposure;',
		HSV_FN,
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float luma = dot(col, vec3(0.299, 0.587, 0.114));',
		'  vec3 mapped = texture2D(u_lut, vec2(clamp(luma, 0.0, 1.0), 0.5)).rgb;',
		'  vec3 hsv = rgb2hsv(mapped);',
		'  hsv.x = fract(hsv.x + u_hue / 360.0);',
		'  hsv.y = clamp(hsv.y * u_saturation, 0.0, 1.0);',
		'  mapped = hsv2rgb(hsv) * u_exposure;',
		'  gl_FragColor = vec4(clamp(mapped, 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const HSV = [
		FILTER,
		'uniform float u_hue;',
		'uniform float u_saturation;',
		'uniform float u_value;',
		HSV_FN,
		'',
		'void main() {',
		'  vec3 hsv = rgb2hsv(src().rgb);',
		'  hsv.x = fract(hsv.x + u_hue / 360.0);',
		'  hsv.y = clamp(hsv.y * u_saturation, 0.0, 1.0);',
		'  hsv.z = clamp(hsv.z * u_value, 0.0, 1.0);',
		'  gl_FragColor = vec4(hsv2rgb(hsv), 1.0);',
		'}'
	].join('\n');

	const LEVELS = [
		FILTER,
		'uniform float u_inBlack;',
		'uniform float u_inWhite;',
		'uniform float u_gamma;',
		'uniform float u_outBlack;',
		'uniform float u_outWhite;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float span = max(u_inWhite - u_inBlack, 1.0e-4);',
		'  vec3 x = clamp((col - u_inBlack) / span, 0.0, 1.0);',
		'  x = pow(max(x, 0.0), vec3(1.0 / max(u_gamma, 0.08)));',
		'  col = mix(vec3(u_outBlack), vec3(u_outWhite), x);',
		'  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const CONTRAST = [
		FILTER,
		'uniform float u_contrast;',
		'uniform float u_brightness;',
		'uniform float u_pivot;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  col = (col - u_pivot) * u_contrast + u_pivot + u_brightness;',
		'  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const RAMP = [
		FILTER,
		'uniform sampler2D u_lut;',
		'uniform float u_phase;',
		'uniform float u_period;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float luma = dot(col, vec3(0.299, 0.587, 0.114));',
		'  float t = luma * u_period + u_phase;',
		'  t = t - floor(t);',
		'  float texel = 0.5 / 256.0;',
		'  vec3 mapped = texture2D(u_lut, vec2(clamp(t, texel, 1.0 - texel), 0.5)).rgb;',
		'  gl_FragColor = vec4(mapped, 1.0);',
		'}'
	].join('\n');

	const BLOOM_BRIGHT = [
		FILTER,
		'uniform float u_threshold;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float luma = dot(col, vec3(0.2126, 0.7152, 0.0722));',
		'  float knee = max(u_threshold * 0.5, 0.001);',
		'  float soft = luma - u_threshold + knee;',
		'  soft = clamp(soft, 0.0, 2.0 * knee);',
		'  soft = (soft * soft) / (4.0 * knee);',
		'  float contrib = max(soft, luma - u_threshold) / max(luma, 1.0e-4);',
		'  gl_FragColor = vec4(col * contrib, 1.0);',
		'}'
	].join('\n');

	const BLOOM_DOWN = [
		FILTER,
		'uniform vec2 u_texel;',
		'uniform float u_offset;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 halfpixel = u_texel * u_offset;',
		'  vec3 sum = texture2D(u_input, st).rgb * 4.0;',
		'  sum += texture2D(u_input, st - halfpixel).rgb;',
		'  sum += texture2D(u_input, st + halfpixel).rgb;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x, -halfpixel.y)).rgb;',
		'  sum += texture2D(u_input, st - vec2(halfpixel.x, -halfpixel.y)).rgb;',
		'  gl_FragColor = vec4(sum / 8.0, 1.0);',
		'}'
	].join('\n');

	const BLOOM_UP = [
		FILTER,
		'uniform vec2 u_texel;',
		'uniform float u_offset;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 halfpixel = u_texel * u_offset;',
		'  vec3 sum = texture2D(u_input, st + vec2(-halfpixel.x * 2.0, 0.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(-halfpixel.x, halfpixel.y)).rgb * 2.0;',
		'  sum += texture2D(u_input, st + vec2(0.0, halfpixel.y * 2.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x, halfpixel.y)).rgb * 2.0;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x * 2.0, 0.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x, -halfpixel.y)).rgb * 2.0;',
		'  sum += texture2D(u_input, st + vec2(0.0, -halfpixel.y * 2.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(-halfpixel.x, -halfpixel.y)).rgb * 2.0;',
		'  gl_FragColor = vec4(sum / 12.0, 1.0);',
		'}'
	].join('\n');

	const BLOOM_COMP = [
		FILTER,
		'uniform sampler2D u_bloom;',
		'uniform float u_intensity;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  vec3 glow = texture2D(u_bloom, uv()).rgb * u_intensity;',
		'  vec3 add = col + glow;',
		'  vec3 screen = vec3(1.0) - (vec3(1.0) - col) * (vec3(1.0) - glow);',
		'  gl_FragColor = vec4(mix(add, screen, 0.55), 1.0);',
		'}'
	].join('\n');

	const EDGE = [
		FILTER,
		'uniform float u_threshold;',
		'uniform float u_intensity;',
		'uniform float u_radius;',
		'uniform float u_mix;',
		'uniform float u_invert;',
		'uniform vec3 u_color;',
		'uniform float u_hasInput;',
		'uniform float u_blendMode;',
		'',
		BLEND_BODY,
		'',
		'float lumaAt(vec2 st) {',
		'  vec3 col = texture2D(u_input, clamp(st, 0.0, 1.0)).rgb;',
		'  return dot(col, vec3(0.299, 0.587, 0.114));',
		'}',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 texel = (1.0 / max(u_resolution, vec2(1.0))) * max(u_radius, 0.15);',
		'  float tl = lumaAt(st + vec2(-texel.x, -texel.y));',
		'  float t  = lumaAt(st + vec2(0.0, -texel.y));',
		'  float tr = lumaAt(st + vec2(texel.x, -texel.y));',
		'  float l  = lumaAt(st + vec2(-texel.x, 0.0));',
		'  float r  = lumaAt(st + vec2(texel.x, 0.0));',
		'  float bl = lumaAt(st + vec2(-texel.x, texel.y));',
		'  float b  = lumaAt(st + vec2(0.0, texel.y));',
		'  float br = lumaAt(st + vec2(texel.x, texel.y));',
		'  float gx = -tl + tr - 2.0 * l + 2.0 * r - bl + br;',
		'  float gy = -tl - 2.0 * t - tr + bl + 2.0 * b + br;',
		'  float mag = length(vec2(gx, gy));',
		'  float edge = clamp((mag - u_threshold) * u_intensity, 0.0, 1.0);',
		'  edge = mix(edge, 1.0 - edge, clamp(u_invert, 0.0, 1.0));',
		'  vec3 srcCol = src().rgb;',
		'  vec3 blended = blendWith(u_color * edge);',
		'  gl_FragColor = vec4(mix(srcCol, blended, clamp(u_mix, 0.0, 1.0)), 1.0);',
		'}'
	].join('\n');

	const COPY = [
		FILTER,
		'uniform float u_gain;',
		'',
		'void main() {',
		'  gl_FragColor = vec4(src().rgb * u_gain, 1.0);',
		'}'
	].join('\n');

	const MASK_SHAPE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform sampler2D u_input;',
		'uniform float u_hasPrev;',
		'uniform float u_shape;',
		'uniform vec2 u_center;',
		'uniform vec2 u_size;',
		'uniform float u_feather;',
		'uniform float u_invert;',
		'',
		'float cover() {',
		'  vec2 px = vTexCoord * u_resolution;',
		'  vec2 c = u_center * u_resolution;',
		'  float m = min(u_resolution.x, u_resolution.y);',
		'  float feather = max(u_feather * m, 1.0);',
		'  float d;',
		'  if (u_shape < 0.5) {',
		'    vec2 halfPx = max(u_size * 0.5 * u_resolution, vec2(1.0));',
		'    vec2 q = abs(px - c) - halfPx;',
		'    d = length(max(q, 0.0)) + min(max(q.x, q.y), 0.0);',
		'  } else {',
		'    float r = max(u_size.x * m, 1.0);',
		'    d = length(px - c) - r;',
		'  }',
		'  return 1.0 - smoothstep(-feather, feather, d);',
		'}',
		'',
		'void main() {',
		'  float prev = u_hasPrev > 0.5 ? texture2D(u_input, vTexCoord).r : 0.0;',
		'  float shape = cover();',
		'  float next = u_invert > 0.5 ? prev * (1.0 - shape) : max(prev, shape);',
		'  gl_FragColor = vec4(next, next, next, 1.0);',
		'}'
	].join('\n');

	const CORNER_PIN = [
		FILTER,
		'uniform sampler2D u_mask;',
		'uniform float u_hasMask;',
		'uniform float u_maskInvert;',
		'uniform vec3 u_h0;',
		'uniform vec3 u_h1;',
		'uniform vec3 u_h2;',
		'',
		'void main() {',
		'  vec3 q = vec3(uv(), 1.0);',
		'  vec3 hp = vec3(dot(u_h0, q), dot(u_h1, q), dot(u_h2, q));',
		'  if (abs(hp.z) < 1.0e-6) {',
		'    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);',
		'    return;',
		'  }',
		'  vec2 st = hp.xy / hp.z;',
		'  if (st.x < 0.0 || st.x > 1.0 || st.y < 0.0 || st.y > 1.0) {',
		'    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);',
		'    return;',
		'  }',
		'  vec3 col = texture2D(u_input, st).rgb;',
		'  float m = 1.0;',
		'  if (u_hasMask > 0.5) {',
		'    m = texture2D(u_mask, st).r;',
		'    m = mix(m, 1.0 - m, clamp(u_maskInvert, 0.0, 1.0));',
		'  }',
		'  gl_FragColor = vec4(col * m, 1.0);',
		'}'
	].join('\n');

	const TEST_CARD = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'',
		'void main() {',
		'  vec2 uv = vTexCoord;',
		'  vec2 p = uv * 2.0 - 1.0;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  vec2 cells = uv * vec2(16.0, 9.0);',
		'  vec2 g = abs(fract(cells) - 0.5);',
		'  float line = 1.0 - smoothstep(0.0, 0.06, min(g.x, g.y));',
		'  float cross = step(abs(uv.x - 0.5), 0.0015) + step(abs(uv.y - 0.5), 0.0015);',
		'  float r = length(p);',
		'  float ring = 0.0;',
		'  ring += 1.0 - smoothstep(0.0, 0.012, abs(r - 0.22));',
		'  ring += 1.0 - smoothstep(0.0, 0.012, abs(r - 0.44));',
		'  ring += 1.0 - smoothstep(0.0, 0.012, abs(r - 0.66));',
		'  float frame = step(min(min(uv.x, 1.0 - uv.x), min(uv.y, 1.0 - uv.y)), 0.018);',
		'  vec3 col = vec3(0.07);',
		'  col += vec3(0.42) * line;',
		'  col += vec3(0.95) * clamp(cross, 0.0, 1.0);',
		'  col += vec3(0.85) * clamp(ring, 0.0, 1.0);',
		'  col = mix(col, vec3(1.0), frame);',
		'  vec2 c = uv;',
		'  if (c.x < 0.08 && c.y < 0.08) col = vec3(0.85, 0.18, 0.16);',
		'  if (c.x > 0.92 && c.y < 0.08) col = vec3(0.18, 0.72, 0.28);',
		'  if (c.x > 0.92 && c.y > 0.92) col = vec3(0.2, 0.45, 0.95);',
		'  if (c.x < 0.08 && c.y > 0.92) col = vec3(0.95, 0.82, 0.18);',
		'  gl_FragColor = vec4(col, 1.0);',
		'}'
	].join('\n');

	const SHAPE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_kind;',
		'uniform vec2 u_center;',
		'uniform vec2 u_size;',
		'uniform float u_sides;',
		'uniform float u_rotation;',
		'uniform float u_feather;',
		'uniform vec3 u_color;',
		BLEND_FN,
		'',
		'float sdBox(vec2 p, vec2 b) {',
		'  vec2 q = abs(p) - b;',
		'  return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0);',
		'}',
		'',
		'float sdPolygon(vec2 p, float n, float radius) {',
		'  float ang = 3.14159265 / max(n, 3.0);',
		'  float a = atan(p.x, p.y);',
		'  float d = cos(floor(0.5 + a / ang) * ang - a) * length(p);',
		'  return d - radius * cos(ang);',
		'}',
		'',
		'void main() {',
		'  vec2 px = vTexCoord * u_resolution;',
		'  vec2 c = u_center * u_resolution;',
		'  float m = min(u_resolution.x, u_resolution.y);',
		'  float feather = max(u_feather * m, 1.0);',
		'  vec2 p = px - c;',
		'  float ang = u_rotation * 0.017453292;',
		'  float cs = cos(ang);',
		'  float sn = sin(ang);',
		'  p = vec2(cs * p.x - sn * p.y, sn * p.x + cs * p.y);',
		'  float d;',
		'  if (u_kind < 0.5) {',
		'    d = length(p) - max(u_size.x * m, 1.0);',
		'  } else if (u_kind < 1.5) {',
		'    vec2 halfPx = max(u_size * 0.5 * u_resolution, vec2(1.0));',
		'    d = sdBox(p, halfPx);',
		'  } else {',
		'    d = sdPolygon(p, max(u_sides, 3.0), max(u_size.x * m, 1.0));',
		'  }',
		'  float v = 1.0 - smoothstep(-feather, feather, d);',
		'  gl_FragColor = vec4(blendWith(u_color * v), 1.0);',
		'}'
	].join('\n');

	const GRADIENT = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_kind;',
		'uniform float u_angle;',
		'uniform float u_position;',
		'uniform float u_spread;',
		'uniform vec3 u_colorA;',
		'uniform vec3 u_colorB;',
		BLEND_FN,
		'',
		'void main() {',
		'  vec2 p = vTexCoord - 0.5;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_angle * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  vec2 q = vec2(c * p.x - s * p.y, s * p.x + c * p.y);',
		'  float t;',
		'  if (u_kind < 0.5) {',
		'    t = q.x * 0.5 + 0.5;',
		'  } else if (u_kind < 1.5) {',
		'    t = length(q) / 0.75;',
		'  } else {',
		'    t = atan(q.y, q.x) / 6.2831853 + 0.5;',
		'  }',
		'  float span = max(u_spread, 0.02);',
		'  t = (t - u_position) / span + 0.5;',
		'  t = clamp(t, 0.0, 1.0);',
		'  gl_FragColor = vec4(blendWith(mix(u_colorA, u_colorB, t)), 1.0);',
		'}'
	].join('\n');

	const DISPLACE = [
		FILTER,
		TILE_FN,
		'uniform float u_amount;',
		'uniform float u_angle;',
		'uniform float u_center;',
		'uniform float u_mode;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec3 map = texture2D(u_input, st).rgb;',
		'  vec2 delta;',
		'  if (u_mode > 0.5) {',
		'    delta = (map.rg - vec2(u_center)) * u_amount;',
		'  } else {',
		'    float luma = dot(map, vec3(0.299, 0.587, 0.114));',
		'    float ang = u_angle * 0.017453292;',
		'    delta = vec2(cos(ang), sin(ang)) * (luma - u_center) * u_amount;',
		'  }',
		'  gl_FragColor = texture2D(u_input, tileUv(st + delta, u_tile));',
		'}'
	].join('\n');

	const BLUR = [
		FILTER,
		'uniform vec2 u_axis;',
		'uniform float u_radius;',
		'uniform float u_mix;',
		'uniform float u_final;',
		'uniform sampler2D u_dry;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 px = u_axis * u_radius / max(u_resolution, vec2(1.0));',
		'  vec3 sum = texture2D(u_input, st).rgb * 0.227027;',
		'  sum += texture2D(u_input, st + px * 1.384615).rgb * 0.316216;',
		'  sum += texture2D(u_input, st - px * 1.384615).rgb * 0.316216;',
		'  sum += texture2D(u_input, st + px * 3.230769).rgb * 0.070270;',
		'  sum += texture2D(u_input, st - px * 3.230769).rgb * 0.070270;',
		'  if (u_final > 0.5) {',
		'    vec3 dry = texture2D(u_dry, st).rgb;',
		'    sum = mix(dry, sum, clamp(u_mix, 0.0, 1.0));',
		'  }',
		'  gl_FragColor = vec4(sum, 1.0);',
		'}'
	].join('\n');

	const FEEDBACK = [
		FILTER,
		TILE_FN,
		'uniform sampler2D u_feedback;',
		'uniform float u_amount;',
		'uniform float u_decay;',
		'uniform float u_scale;',
		'uniform float u_rotate;',
		'uniform vec2 u_offset;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv() - 0.5;',
		'  st.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_rotate * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  st = vec2(c * st.x - s * st.y, s * st.x + c * st.y);',
		'  st *= max(u_scale, 0.2);',
		'  st.x /= u_resolution.x / max(u_resolution.y, 1.0);',
		'  st += 0.5 + u_offset;',
		'  vec3 trail = texture2D(u_feedback, tileUv(st, u_tile)).rgb * clamp(u_decay, 0.0, 1.0);',
		'  vec3 src = src().rgb;',
		'  gl_FragColor = vec4(clamp(mix(src, src + trail, clamp(u_amount, 0.0, 1.0)), 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const GLITCH = [
		FILTER,
		TILE_FN,
		'uniform float u_amount;',
		'uniform float u_speed;',
		'uniform float u_narrowness;',
		'uniform float u_blockiness;',
		'uniform float u_sparsity;',
		'uniform float u_chroma;',
		'uniform float u_angle;',
		'uniform float u_tile;',
		'',
		'float satf(float t) {',
		'  return clamp(t, 0.0, 1.0);',
		'}',
		'',
		'float remap01(float t, float a, float b) {',
		'  return satf((t - a) / max(b - a, 1.0e-4));',
		'}',
		'',
		'float linterp(float t) {',
		'  return satf(1.0 - abs(2.0 * t - 1.0));',
		'}',
		'',
		'float qstep(float x, float levels) {',
		'  float n = max(levels, 1.0);',
		'  return floor(x * n) / n;',
		'}',
		'',
		'vec2 qstep2(vec2 x, float levels) {',
		'  float n = max(levels, 1.0);',
		'  return floor(x * n) / n;',
		'}',
		'',
		'float hash21(vec2 n) {',
		'  return fract(sin(dot(n, vec2(12.9898, 78.233))) * 43758.5453);',
		'}',
		'',
		'float glitchRand(vec2 p, float t) {',
		'  vec2 k = vec2(12.9898, 78.233) * (t + 1.17);',
		'  return fract(sin(dot(p, k)) * 43758.5453);',
		'}',
		'',
		'float glitchNoise(vec2 st, float blockiness, float t) {',
		'  vec2 lv = fract(st);',
		'  vec2 id = floor(st);',
		'  float n1 = glitchRand(id, t);',
		'  float n2 = glitchRand(id + vec2(1.0, 0.0), t);',
		'  float n3 = glitchRand(id + vec2(0.0, 1.0), t);',
		'  float n4 = glitchRand(id + vec2(1.0, 1.0), t);',
		'  vec2 u = smoothstep(0.0, 1.0 + blockiness, lv);',
		'  return mix(mix(n1, n2, u.x), mix(n3, n4, u.x), u.y);',
		'}',
		'',
		'float glitchFbm(vec2 st, float blockiness, float complexity, float t) {',
		'  float val = 0.0;',
		'  float amp = 0.5;',
		'  for (int i = 0; i < 4; i++) {',
		'    val += amp * glitchNoise(st, blockiness, t);',
		'    amp *= 0.5;',
		'    st *= complexity;',
		'  }',
		'  return val;',
		'}',
		'',
		'vec3 spectrumOffset(float t) {',
		'  float lo = step(t, 0.5);',
		'  float hi = 1.0 - lo;',
		'  float w = linterp(remap01(t, 0.1666667, 0.8333333));',
		'  vec3 ret = vec3(lo, 1.0, hi) * vec3(1.0 - w, w, 1.0 - w);',
		'  return pow(max(ret, vec3(0.0)), vec3(0.45454545));',
		'}',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  float amount = satf(u_amount);',
		'  if (amount < 0.0001) {',
		'    gl_FragColor = texture2D(u_input, st);',
		'    return;',
		'  }',
		'  float aspect = u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_angle * 0.017453292;',
		'  float cs = cos(ang);',
		'  float sn = sin(ang);',
		'  vec2 dir = vec2(cs, sn);',
		'  vec2 perp = vec2(-sn, cs);',
		'  vec2 q = st - 0.5;',
		'  q.x *= aspect;',
		'  q = vec2(cs * q.x + sn * q.y, -sn * q.x + cs * q.y);',
		'  q.x /= aspect;',
		'  vec2 local = q + 0.5;',
		'  float hz = max(u_speed, 0.0) * 4.0;',
		'  float seed = hz < 1.0e-4 ? 0.0 : floor(u_time * hz);',
		'  float gtime = seed;',
		'  float tick = seed * 0.13;',
		'  float gnm = amount;',
		'  float rnd0 = hash21(qstep2(vec2(gtime, gtime), 6.0));',
		'  float r0 = satf((1.0 - gnm) * 0.7 + rnd0);',
		'  float strips = mix(6.0, 72.0, satf((u_narrowness - 0.5) / 15.5));',
		'  float rnd1 = hash21(vec2(qstep(local.x, 10.0 * r0), gtime));',
		'  float r1 = 0.5 - 0.5 * gnm + rnd1;',
		'  r1 = 1.0 - max(0.0, min(r1, 0.9999999));',
		'  float rnd2 = hash21(vec2(qstep(local.y, strips * r1), gtime));',
		'  float r2 = satf(rnd2);',
		'  float rnd3 = hash21(vec2(qstep(local.y, 10.0 * r0), gtime));',
		'  float r3 = (1.0 - satf(rnd3 + 0.8)) - 0.1;',
		'  float pxrnd = hash21(local + gtime);',
		'  float rare = satf((u_sparsity - 1.0) / 15.0);',
		'  float cut = mix(0.02, 0.84, rare);',
		'  float live = smoothstep(cut, min(cut + mix(0.38, 0.07, rare), 1.0), r2);',
		'  float stripOfs = 0.05 * r2 * gnm * (rnd0 > 0.5 ? 1.0 : -1.0);',
		'  stripOfs += 0.5 * pxrnd * stripOfs;',
		'  vec2 domain = vec2(local.x * aspect * 0.45 + 5.13, local.y * max(u_narrowness, 0.5) + 3.71);',
		'  float n = clamp(glitchFbm(domain, u_blockiness, max(u_narrowness, 0.5), tick), 0.0, 1.0);',
		'  live *= mix(1.0, pow(max(n, 1.0e-6), mix(1.0, 4.0, rare)), rare * 0.7);',
		'  float ofs = stripOfs * live;',
		'  ofs += (n * 2.0 - 1.0) * amount * 0.1 * live;',
		'  vec2 base = st + perp * (0.1 * r3 * gnm * live);',
		'  float smear = max(u_chroma, 0.0);',
		'  vec3 col;',
		'  if (smear < 0.01) {',
		'    col = texture2D(u_input, tileUv(base + dir * ofs, u_tile)).rgb;',
		'  } else {',
		'    vec3 sum = vec3(0.0);',
		'    vec3 wsum = vec3(0.0);',
		'    for (int i = 0; i < 8; i++) {',
		'      float t = float(i) * 0.125;',
		'      vec3 w = mix(vec3(1.0), spectrumOffset(t), satf(smear));',
		'      vec2 suv = base + dir * (ofs * t * smear);',
		'      sum += texture2D(u_input, tileUv(suv, u_tile)).rgb * w;',
		'      wsum += w;',
		'    }',
		'    col = sum / max(wsum, vec3(1.0e-4));',
		'  }',
		'  gl_FragColor = vec4(col, 1.0);',
		'}'
	].join('\n');

	const TAPE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_time;',
		'uniform float u_speed;',
		'uniform float u_lines;',
		'uniform float u_threshold;',
		'uniform float u_grain;',
		'uniform float u_amount;',
		BLEND_FN,
		'',
		'vec4 hash42(vec2 p) {',
		'  vec4 p4 = fract(vec4(p.xyxy) * vec4(443.8975, 397.2973, 491.1871, 470.7827));',
		'  p4 += dot(p4.wzxy, p4 + 19.19);',
		'  return fract(vec4(p4.x * p4.y, p4.x * p4.z, p4.y * p4.w, p4.x * p4.w));',
		'}',
		'',
		'float hash1(float n) {',
		'  return fract(sin(n) * 43758.5453123);',
		'}',
		'',
		'float iqNoise(vec3 x) {',
		'  vec3 p = floor(x);',
		'  vec3 f = fract(x);',
		'  f = f * f * (3.0 - 2.0 * f);',
		'  float n = p.x + p.y * 57.0 + 113.0 * p.z;',
		'  return mix(',
		'    mix(',
		'      mix(hash1(n + 0.0), hash1(n + 1.0), f.x),',
		'      mix(hash1(n + 57.0), hash1(n + 58.0), f.x),',
		'      f.y',
		'    ),',
		'    mix(',
		'      mix(hash1(n + 113.0), hash1(n + 114.0), f.x),',
		'      mix(hash1(n + 170.0), hash1(n + 171.0), f.x),',
		'      f.y',
		'    ),',
		'    f.z',
		'  );',
		'}',
		'',
		'float tapeNoise(vec2 p, float t) {',
		'  float y = p.y;',
		'  float s = t * u_speed;',
		'  float v = iqNoise(vec3(y * 0.01 + s, 1.0, 1.0));',
		'  v *= iqNoise(vec3(y * 0.011 + 1000.0 + s, 1.0, 1.0));',
		'  v *= iqNoise(vec3(y * 0.51 + 421.0 + s, 1.0, 1.0));',
		'  float cell = hash42(vec2(p.x + t * 0.01, p.y)).x + 0.3;',
		'  v *= mix(1.0, cell, clamp(u_grain, 0.0, 2.0));',
		'  v = v + 0.3;',
		'  v *= step(u_threshold, v);',
		'  return v * u_amount;',
		'}',
		'',
		'void main() {',
		'  vec2 frag = vTexCoord * u_resolution;',
		'  float oneY = u_resolution.y / max(u_lines, 1.0);',
		'  vec2 p = floor(frag / oneY) * oneY;',
		'  float col = tapeNoise(p, u_time);',
		'  gl_FragColor = vec4(blendWith(vec3(col)), 1.0);',
		'}'
	].join('\n');

	const TRANSFORM = [
		FILTER,
		TILE_FN,
		'uniform vec2 u_translate;',
		'uniform float u_rotate;',
		'uniform vec2 u_scale;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv() - 0.5;',
		'  st -= u_translate;',
		'  float aspect = u_resolution.x / max(u_resolution.y, 1.0);',
		'  st.x *= aspect;',
		'  float ang = -u_rotate * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  st = vec2(c * st.x - s * st.y, s * st.x + c * st.y);',
		'  vec2 sc = max(u_scale, vec2(0.001));',
		'  st /= sc;',
		'  st.x /= aspect;',
		'  st += 0.5;',
		'  gl_FragColor = texture2D(u_input, tileUv(st, u_tile));',
		'}'
	].join('\n');

	const PIXELATE = [
		FILTER,
		'uniform vec2 u_size;',
		'uniform float u_mix;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 cell = max(u_size, vec2(1.0));',
		'  vec2 grid = max(u_resolution / cell, vec2(1.0));',
		'  vec2 snapped = (floor(st * grid) + 0.5) / grid;',
		'  vec3 wet = texture2D(u_input, clamp(snapped, 0.0, 1.0)).rgb;',
		'  gl_FragColor = vec4(mix(src().rgb, wet, clamp(u_mix, 0.0, 1.0)), 1.0);',
		'}'
	].join('\n');

	const POSTERIZE = [
		FILTER,
		'uniform float u_levels;',
		'uniform float u_mix;',
		'uniform float u_mode;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float n = max(u_levels, 2.0);',
		'  vec3 wet;',
		'  if (u_mode > 0.5) {',
		'    float luma = dot(col, vec3(0.299, 0.587, 0.114));',
		'    float q = floor(luma * n) / n;',
		'    wet = col * (q / max(luma, 1.0e-4));',
		'  } else {',
		'    wet = floor(col * n) / n;',
		'  }',
		'  gl_FragColor = vec4(mix(col, clamp(wet, 0.0, 1.0), clamp(u_mix, 0.0, 1.0)), 1.0);',
		'}'
	].join('\n');

	const MIRROR = [
		FILTER,
		TILE_FN,
		'uniform float u_axis;',
		'uniform float u_mode;',
		'uniform float u_offsetX;',
		'uniform float u_offsetY;',
		'uniform float u_angle;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv() - 0.5;',
		'  float aspect = u_resolution.x / max(u_resolution.y, 1.0);',
		'  st.x *= aspect;',
		'  float ang = u_angle * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  st = vec2(c * st.x - s * st.y, s * st.x + c * st.y);',
		'  st.x /= aspect;',
		'  st += 0.5;',
		'  if (u_mode < 0.5) {',
		'    if (u_axis < 0.5 || u_axis > 1.5) st.x = u_offsetX + abs(st.x - u_offsetX);',
		'    if (u_axis > 0.5) st.y = u_offsetY + abs(st.y - u_offsetY);',
		'  } else {',
		'    if (u_axis < 0.5 || u_axis > 1.5) st.x = u_offsetX - (st.x - u_offsetX);',
		'    if (u_axis > 0.5) st.y = u_offsetY - (st.y - u_offsetY);',
		'  }',
		'  gl_FragColor = texture2D(u_input, tileUv(st, u_tile));',
		'}'
	].join('\n');

	const TILE = [
		FILTER,
		TILE_FN,
		'uniform vec2 u_count;',
		'uniform vec2 u_offset;',
		'uniform float u_angle;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv() - 0.5;',
		'  float aspect = u_resolution.x / max(u_resolution.y, 1.0);',
		'  st.x *= aspect;',
		'  float ang = -u_angle * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  st = vec2(c * st.x - s * st.y, s * st.x + c * st.y);',
		'  st.x /= aspect;',
		'  st += 0.5;',
		'  vec2 count = max(u_count, vec2(0.25));',
		'  st = (st - 0.5) * count + 0.5 + u_offset;',
		'  gl_FragColor = texture2D(u_input, tileUv(st, u_tile));',
		'}'
	].join('\n');

	const INVERT = [
		FILTER,
		HSV_FN,
		'uniform float u_amount;',
		'uniform float u_mode;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  vec3 inv;',
		'  if (u_mode < 0.5) {',
		'    inv = 1.0 - col;',
		'  } else if (u_mode < 1.5) {',
		'    vec3 hsv = rgb2hsv(col);',
		'    hsv.z = 1.0 - hsv.z;',
		'    inv = hsv2rgb(hsv);',
		'  } else {',
		'    vec3 hsv = rgb2hsv(col);',
		'    hsv.x = fract(hsv.x + 0.5);',
		'    inv = hsv2rgb(hsv);',
		'  }',
		'  gl_FragColor = vec4(mix(col, inv, clamp(u_amount, 0.0, 1.0)), 1.0);',
		'}'
	].join('\n');

	const CHROMA_KEY = [
		FILTER,
		'uniform vec3 u_key;',
		'uniform vec3 u_fill;',
		'uniform float u_tolerance;',
		'uniform float u_softness;',
		'uniform float u_spill;',
		'uniform float u_invert;',
		'uniform float u_match;',
		'',
		'vec2 rgb2cbcr(vec3 c) {',
		'  return vec2(',
		'    -0.168736 * c.r - 0.331264 * c.g + 0.5 * c.b,',
		'    0.5 * c.r - 0.418688 * c.g - 0.081312 * c.b',
		'  );',
		'}',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float dist;',
		'  if (u_match < 0.5) {',
		'    dist = distance(rgb2cbcr(col), rgb2cbcr(u_key)) * 1.75;',
		'  } else {',
		'    dist = distance(col, u_key);',
		'  }',
		'  float t0 = max(u_tolerance, 0.0);',
		'  float t1 = t0 + max(u_softness, 1.0e-4);',
		'  float keep = smoothstep(t0, t1, dist);',
		'  if (u_invert > 0.5) keep = 1.0 - keep;',
		'  vec3 lumaW = vec3(0.299, 0.587, 0.114);',
		'  vec3 keyChroma = u_key - vec3(dot(u_key, lumaW));',
		'  float keyLen = length(keyChroma);',
		'  vec3 cleaned = col;',
		'  if (keyLen > 0.001) {',
		'    vec3 n = keyChroma / keyLen;',
		'    float along = max(dot(col - vec3(dot(col, lumaW)), n), 0.0);',
		'    float fringe = keep * (1.0 - smoothstep(t0, t1 + 0.22, dist));',
		'    cleaned = col - n * along * clamp(u_spill, 0.0, 1.0) * fringe;',
		'  }',
		'  gl_FragColor = vec4(clamp(mix(u_fill, cleaned, keep), 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const WARPED_CONSTELLATIONS = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_time;',
		'uniform float u_speed;',
		'uniform float u_travel;',
		'uniform float u_scale;',
		'uniform float u_glow;',
		'uniform float u_hue;',
		'uniform float u_warp;',
		'',
		'#define TIME (u_time * u_speed)',
		'#define ROT(a) mat2(cos(a), sin(a), -sin(a), cos(a))',
		'#define SAT(x) clamp(x, 0.0, 1.0)',
		'',
		'const float pi = 3.14159265;',
		'const float tau = 6.2831853;',
		'const float pi_2 = 1.5707963;',
		'const float planeDist = 0.5;',
		'const float furthest = 6.0;',
		'const float fadeFrom = 4.0;',
		'const vec3 LD = vec3(0.0, 0.8741573, 0.4856429);',
		'const vec2 pathA = vec2(0.31, 0.41);',
		'const vec2 pathB = vec2(1.0, 0.70710678);',
		BLEND_FN,
		'',
		'vec3 acesApprox(vec3 v) {',
		'  v = max(v, 0.0);',
		'  v *= 0.6;',
		'  float a = 2.51;',
		'  float b = 0.03;',
		'  float c = 2.43;',
		'  float d = 0.59;',
		'  float e = 0.14;',
		'  return clamp((v * (a * v + b)) / (v * (c * v + d) + e), 0.0, 1.0);',
		'}',
		'',
		'vec3 pathOffset(float z) {',
		'  return vec3(pathB * sin(pathA * z), z);',
		'}',
		'',
		'vec3 pathDOffset(float z) {',
		'  return vec3(pathA * pathB * cos(pathA * z), 1.0);',
		'}',
		'',
		'vec3 pathDDOffset(float z) {',
		'  return vec3(-pathA * pathA * pathB * sin(pathA * z), 0.0);',
		'}',
		'',
		'float hash1(float co) {',
		'  co += 123.4;',
		'  return fract(sin(co * 12.9898) * 13758.5453);',
		'}',
		'',
		'float hash2(vec2 co) {',
		'  co += 123.4;',
		'  return fract(sin(dot(co.xy, vec2(12.9898, 58.233))) * 13758.5453);',
		'}',
		'',
		'float atanApprox(float y, float x) {',
		'  float cosatan2 = x / max(abs(x) + abs(y), 1.0e-6);',
		'  float t = pi_2 - cosatan2 * pi_2;',
		'  return y < 0.0 ? -t : t;',
		'}',
		'',
		'float acosApprox(float x) {',
		'  x = clamp(x, -1.0, 1.0);',
		'  return atanApprox(sqrt(max(1.0 - x * x, 0.0)), x);',
		'}',
		'',
		'vec4 hextile(vec2 p) {',
		'  vec2 sz = vec2(1.0, 1.7320508);',
		'  vec2 hsz = 0.5 * sz;',
		'  vec2 p1 = mod(p, sz) - hsz;',
		'  vec2 p2 = mod(p - hsz, sz) - hsz;',
		'  vec2 p3 = dot(p1, p1) < dot(p2, p2) ? p1 : p2;',
		'  vec2 n = (p3 - p + hsz) / sz;',
		'  n -= vec2(0.5);',
		'  n = floor(n * 2.0 + 0.5) * 0.5;',
		'  return vec4(p3, n);',
		'}',
		'',
		'float dot2(vec2 p) {',
		'  return dot(p, p);',
		'}',
		'',
		'float bezier(vec2 pos, vec2 A, vec2 B, vec2 C) {',
		'  vec2 a = B - A;',
		'  vec2 b = A - 2.0 * B + C;',
		'  vec2 c = a * 2.0;',
		'  vec2 d = A - pos;',
		'  float kk = 1.0 / max(dot(b, b), 1.0e-6);',
		'  float kx = kk * dot(a, b);',
		'  float ky = kk * (2.0 * dot(a, a) + dot(d, b)) / 3.0;',
		'  float kz = kk * dot(d, a);',
		'  float res = 0.0;',
		'  float p = ky - kx * kx;',
		'  float p3 = p * p * p;',
		'  float q = kx * (2.0 * kx * kx - 3.0 * ky) + kz;',
		'  float h = q * q + 4.0 * p3;',
		'  vec2 x;',
		'  vec2 uv;',
		'  float t;',
		'  float z;',
		'  float v;',
		'  float m;',
		'  float n;',
		'  vec3 ts;',
		'  if (h >= 0.0) {',
		'    h = sqrt(h);',
		'    x = (vec2(h, -h) - q) / 2.0;',
		'    uv = sign(x) * pow(abs(x) + 1.0e-6, vec2(1.0 / 3.0));',
		'    t = clamp(uv.x + uv.y - kx, 0.0, 1.0);',
		'    res = dot2(d + (c + b * t) * t);',
		'  } else {',
		'    z = sqrt(max(-p, 0.0));',
		'    v = acosApprox(q / max(p * z * 2.0, 1.0e-6)) / 3.0;',
		'    m = cos(v);',
		'    n = sin(v) * 1.732050808;',
		'    ts = clamp(vec3(m + m, -n - m, n - m) * z - kx, 0.0, 1.0);',
		'    res = min(dot2(d + (c + b * ts.x) * ts.x), dot2(d + (c + b * ts.y) * ts.y));',
		'  }',
		'  return sqrt(res);',
		'}',
		'',
		'vec3 godray(vec3 bg, vec3 r) {',
		'  float x = atanApprox(r.x, r.z);',
		'  float y = pi * 0.5 - acosApprox(r.y);',
		'  x *= 0.5;',
		'  y *= 0.5;',
		'  vec3 col = bg * (1.0 + y);',
		'  float t = TIME;',
		'  float a = sin(r.x);',
		'  float beam = SAT(sin(10.0 * x + a * y * 5.0 + t));',
		'  beam *= SAT(sin(7.0 * x + a * y * 3.5 - t));',
		'  float beam2 = SAT(sin(42.0 * x + a * y * 21.0 - t));',
		'  beam2 *= SAT(sin(34.0 * x + a * y * 17.0 + t));',
		'  beam += beam2;',
		'  col += beam * 0.25 * sqrt(max(bg, vec3(0.0)));',
		'  return col;',
		'}',
		'',
		'vec2 coff(float h) {',
		'  float h0 = h;',
		'  float h1 = fract(h0 * 9677.0);',
		'  float t = 0.75 * mix(0.5, 1.0, h0 * h0) * (TIME + 1234.5);',
		'  return mix(0.1, 0.2, h1 * h1) * sin(t * vec2(1.0, 0.70710678));',
		'}',
		'',
		'vec2 hexOff(int i) {',
		'  if (i == 0) return vec2(1.0, 0.0);',
		'  if (i == 1) return vec2(0.5, -0.8660254);',
		'  if (i == 2) return vec2(-0.5, -0.8660254);',
		'  if (i == 3) return vec2(-1.0, 0.0);',
		'  if (i == 4) return vec2(-0.5, 0.8660254);',
		'  return vec2(0.5, 0.8660254);',
		'}',
		'',
		'vec2 hexNOff(int i) {',
		'  if (i == 0) return vec2(-1.0, 0.0);',
		'  if (i == 1) return vec2(-0.5, 0.5);',
		'  if (i == 2) return vec2(0.5, 0.5);',
		'  if (i == 3) return vec2(1.0, 0.0);',
		'  if (i == 4) return vec2(0.5, -0.5);',
		'  return vec2(-0.5, -0.5);',
		'}',
		'',
		'vec3 constellationPlane(vec3 ro, vec3 pp, float pd, vec3 off, float n) {',
		'  float ppd = pp.z - ro.z;',
		'  vec2 p = (pp - off * vec3(1.0, 1.0, 0.0)).xy;',
		'  float hh = hash1(n);',
		'  p *= mix(1.125, 1.5, hh * hh);',
		'  vec2 p2 = p;',
		'  mat2 rot = ROT(tau * 0.125 * n + 0.0005 * TIME);',
		'  p2 *= rot;',
		'  p2 += -vec2(0.0, hh * 0.25 * (ro.z - pp.z)) * rot;',
		'  vec2 hp = p2;',
		'  hp += 0.5;',
		'  hp /= (1.0 / 3.0) * max(u_scale, 0.05);',
		'  vec4 tiled = hextile(hp);',
		'  hp = tiled.xy;',
		'  vec2 hn = tiled.zw;',
		'  float h0 = hash2(hn + n);',
		'  vec2 p0 = coff(h0);',
		'  vec3 bcol = (1.0 / 3.0) * (1.0 + cos(vec3(0.0, 1.0, 2.0) + 2.0 * (p2.x + p2.x) - 0.33 * n + u_hue));',
		'  vec3 col = vec3(0.0);',
		'  float mx = 0.00025 + 0.0005 * max(pd - 1.5, 0.0);',
		'  for (int i = 0; i < 6; i++) {',
		'    float h1 = hash2(hn + hexNOff(i) + n);',
		'    vec2 p1 = hexOff(i) + coff(h1);',
		'    float h2 = h0 + h1;',
		'    float fade = smoothstep(1.05, 0.85, distance(p0, p1));',
		'    vec2 mid = 0.5 * (p1 + p0) + coff(h2);',
		'    float dd = bezier(hp, p0, mid, p1);',
		'    float gd = abs(dd);',
		'    gd *= sqrt(max(gd, 0.0));',
		'    gd = max(gd, mx);',
		'    col += step(0.0125, fade) * fade * 0.002 * bcol / gd;',
		'  }',
		'  float cd = length(hp - p0);',
		'  float starGd = abs(cd);',
		'  starGd *= starGd;',
		'  starGd = max(starGd, mx);',
		'  float fd = ppd - 5.0;',
		'  float starFade = hash1(floor(TIME * 5.0 + 123.0 * h0)) > (fd + length(hn)) ? 1.0 : 0.125;',
		'  col += 0.0025 * starFade * sqrt(max(bcol, vec3(0.0))) / starGd;',
		'  col *= 1.25 * u_glow;',
		'  return col;',
		'}',
		'',
		'float hf0(vec2 p) {',
		'  float h = 0.5 + 0.5 * sin(p.x) * sin(p.y);',
		'  h *= h;',
		'  h *= h;',
		'  h *= h;',
		'  return -h;',
		'}',
		'',
		'float hf(vec2 p) {',
		'  float aa = 0.66;',
		'  mat2 pp = 2.03 * ROT(1.0);',
		'  float a = 1.0;',
		'  float h = 0.0;',
		'  float ta = 0.0;',
		'  for (int i = 0; i < 3; i++) {',
		'    p += a * 0.05 * TIME;',
		'    h += a * hf0(p);',
		'    a *= aa;',
		'    ta += a;',
		'    p *= pp;',
		'  }',
		'  return 0.1 * h / max(ta, 1.0e-6);',
		'}',
		'',
		'vec3 nf(vec2 p) {',
		'  vec2 e = vec2(4.0 / max(u_resolution.y, 1.0), 0.0);',
		'  vec3 n;',
		'  n.x = hf(p + e.xy) - hf(p - e.xy);',
		'  n.y = hf(p + e.yx) - hf(p - e.yx);',
		'  n.z = -2.0 * e.x;',
		'  return normalize(n);',
		'}',
		'',
		'vec3 fieldColor(vec3 ww, vec3 uu, vec3 vv, vec3 ro, vec2 p) {',
		'  float rdd = 1.75;',
		'  vec3 rd = normalize(p.x * uu + p.y * vv + rdd * ww);',
		'  float nz = floor(ro.z / planeDist);',
		'  vec3 acol = vec3(0.0);',
		'  vec3 aro = ro;',
		'  float apd = 0.0;',
		'  vec3 ard = rd;',
		'  for (int i = 1; i < 7; i++) {',
		'    float fi = float(i);',
		'    float pz = planeDist * nz + planeDist * fi;',
		'    float lpd = (pz - aro.z) / max(ard.z, 1.0e-4);',
		'    vec3 pp = aro + ard * lpd;',
		'    vec3 nor = nf(pp.xy);',
		'    apd += lpd;',
		'    vec3 off = pathOffset(pp.z);',
		'    float dz = pp.z - ro.z;',
		'    float fadeIn = smoothstep(planeDist * furthest, planeDist * fadeFrom, dz);',
		'    float fadeOut = smoothstep(0.0, planeDist * 0.1, dz);',
		'    float fadeOutRI = smoothstep(0.0, planeDist * 1.0, dz);',
		'    float ri = mix(1.0, 1.0 - 0.1 * u_warp, fadeOutRI * fadeIn);',
		'    vec3 refr = refract(ard, nor, ri);',
		'    vec3 pcol = constellationPlane(ro, pp, apd, off, nz + fi);',
		'    pcol *= fadeOut * fadeIn;',
		'    pcol *= exp(-vec3(0.8, 0.9, 0.7) * apd);',
		'    acol += pcol;',
		'    aro = pp;',
		'    ard = dot(refr, refr) > 0.001 ? refr : ard;',
		'  }',
		'  float lf = 1.001 - dot(ard, LD);',
		'  lf *= lf;',
		'  acol += godray(0.025 * vec3(0.0, 0.25, 1.0) / max(lf, 1.0e-4), rd);',
		'  return acol;',
		'}',
		'',
		'void main() {',
		'  vec2 r = u_resolution.xy;',
		'  vec2 q = vTexCoord;',
		'  vec2 pp = -1.0 + 2.0 * q;',
		'  vec2 p = pp;',
		'  p.x *= r.x / max(r.y, 1.0);',
		'  float tm = 0.125 * planeDist * TIME + u_travel - 0.1 * sin(0.25 * TIME - pp.y + pp.x) * length(pp);',
		'  vec3 ro = pathOffset(tm);',
		'  vec3 dro = pathDOffset(tm);',
		'  vec3 ddro = pathDDOffset(tm);',
		'  vec3 ww = normalize(dro);',
		'  vec3 uu = normalize(cross(vec3(0.0, 1.0, 0.0) + ddro, ww));',
		'  vec3 vv = cross(ww, uu);',
		'  vec3 col = fieldColor(ww, uu, vv, ro, p);',
		'  col -= (1.0 / 30.0) * vec3(2.0, 3.0, 0.0) * (length(pp) + 0.125);',
		'  col *= smoothstep(1.5, 0.70710678, length(pp));',
		'  col = acesApprox(col);',
		'  col = sqrt(max(col, vec3(0.0)));',
		'  gl_FragColor = vec4(blendWith(col), 1.0);',
		'}'
	].join('\n');

	root.SYNTH_SHADERS = {
		vert: VERT,
		lines: LINES,
		noise: NOISE,
		camera: CAMERA,
		warp: WARP,
		lookup: LOOKUP,
		ramp: RAMP,
		hsv: HSV,
		levels: LEVELS,
		contrast: CONTRAST,
		kaleidoscope: KALEIDOSCOPE,
		bloomBright: BLOOM_BRIGHT,
		bloomDown: BLOOM_DOWN,
		bloomUp: BLOOM_UP,
		bloomComp: BLOOM_COMP,
		edge: EDGE,
		copy: COPY,
		maskShape: MASK_SHAPE,
		cornerPin: CORNER_PIN,
		testCard: TEST_CARD,
		shape: SHAPE,
		gradient: GRADIENT,
		displace: DISPLACE,
		blur: BLUR,
		feedback: FEEDBACK,
		transform: TRANSFORM,
		glitch: GLITCH,
		tape: TAPE,
		pixelate: PIXELATE,
		posterize: POSTERIZE,
		mirror: MIRROR,
		tile: TILE,
		invert: INVERT,
		chromaKey: CHROMA_KEY,
		warpedConstellations: WARPED_CONSTELLATIONS
	};
})(window);
