(function (root) {
	const VERT = [
		'attribute vec3 aPosition;',
		'attribute vec2 aTexCoord;',
		'uniform mat4 uProjectionMatrix;',
		'uniform mat4 uModelViewMatrix;',
		'varying vec2 vTexCoord;',
		'void main() {',
		'  vTexCoord = aTexCoord;',
		'  gl_Position = uProjectionMatrix * uModelViewMatrix * vec4(aPosition, 1.0);',
		'}'
	].join('\n');

	const FILTER = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_time;',
		'uniform sampler2D u_input;',
		'',
		'vec2 uv() {',
		'  return vTexCoord;',
		'}',
		'',
		'vec4 src() {',
		'  return texture2D(u_input, uv());',
		'}'
	].join('\n');

	const TILE_FN = [
		'vec2 tileUv(vec2 st, float mode) {',
		'  if (mode < 0.5) return clamp(st, 0.0, 1.0);',
		'  if (mode < 1.5) return fract(st);',
		'  return abs(fract(st * 0.5 + 0.5) * 2.0 - 1.0);',
		'}'
	].join('\n');

	const BLEND_FN = [
		'uniform sampler2D u_input;',
		'uniform float u_hasInput;',
		'uniform float u_blendMode;',
		'',
		'vec3 blendWith(vec3 gen) {',
		'  if (u_hasInput < 0.5) return gen;',
		'  vec3 prev = texture2D(u_input, vTexCoord).rgb;',
		'  if (u_blendMode < 0.5) return gen;',
		'  if (u_blendMode < 1.5) return min(prev + gen, 1.0);',
		'  if (u_blendMode < 2.5) return prev * gen;',
		'  if (u_blendMode < 3.5) return vec3(1.0) - (vec3(1.0) - prev) * (vec3(1.0) - gen);',
		'  if (u_blendMode < 4.5) return abs(prev - gen);',
		'  if (u_blendMode < 5.5) {',
		'    vec3 low = 2.0 * prev * gen;',
		'    vec3 high = vec3(1.0) - 2.0 * (vec3(1.0) - prev) * (vec3(1.0) - gen);',
		'    return mix(low, high, step(0.5, prev));',
		'  }',
		'  if (u_blendMode < 6.5) return max(prev - gen, 0.0);',
		'  if (u_blendMode < 7.5) return max(prev, gen);',
		'  return min(prev, gen);',
		'}'
	].join('\n');

	const LINES = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_fuzzyness;',
		'uniform float u_amount;',
		'uniform float u_width;',
		'uniform float u_rotation;',
		'uniform float u_position;',
		'uniform vec3 u_color;',
		BLEND_FN,
		'',
		'void main() {',
		'  vec2 p = vTexCoord * 2.0 - 1.0;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_rotation * 0.017453292;',
		'  vec2 dir = vec2(sin(ang), cos(ang));',
		'  float n = u_amount;',
		'  float coord = dot(p, dir) * 0.5 + 0.5 + u_position;',
		'  float g = abs(fract(coord * max(n, 1.0)) - 0.5) * 2.0;',
		'  float halfW = clamp(u_width, 0.0, 1.0);',
		'  float fuzz = mix(0.003, 0.5, clamp(u_fuzzyness, 0.0, 1.0));',
		'  float v = (1.0 - smoothstep(halfW, halfW + fuzz, g)) * step(0.5, n);',
		'  gl_FragColor = vec4(blendWith(u_color * v), 1.0);',
		'}'
	].join('\n');

	const NOISE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_time;',
		'uniform float u_scale;',
		'uniform vec3 u_translate;',
		'uniform vec3 u_speed;',
		'uniform float u_amplitude;',
		'uniform float u_offset;',
		'uniform float u_octaves;',
		'uniform float u_contrast;',
		BLEND_FN,
		'',
		'float hash(vec3 p) {',
		'  p = fract(p * 0.1031);',
		'  p += dot(p, p.zyx + 33.33);',
		'  return fract((p.x + p.y) * p.z);',
		'}',
		'',
		'float valueNoise(vec3 p) {',
		'  vec3 i = floor(p);',
		'  vec3 f = fract(p);',
		'  vec3 u = f * f * (3.0 - 2.0 * f);',
		'  return mix(',
		'    mix(',
		'      mix(hash(i), hash(i + vec3(1.0, 0.0, 0.0)), u.x),',
		'      mix(hash(i + vec3(0.0, 1.0, 0.0)), hash(i + vec3(1.0, 1.0, 0.0)), u.x),',
		'      u.y',
		'    ),',
		'    mix(',
		'      mix(hash(i + vec3(0.0, 0.0, 1.0)), hash(i + vec3(1.0, 0.0, 1.0)), u.x),',
		'      mix(hash(i + vec3(0.0, 1.0, 1.0)), hash(i + vec3(1.0, 1.0, 1.0)), u.x),',
		'      u.y',
		'    ),',
		'    u.z',
		'  );',
		'}',
		'',
		'float fbm(vec3 p) {',
		'  float sum = 0.0;',
		'  float amp = 0.5;',
		'  float norm = 0.0;',
		'  for (int i = 0; i < 6; i++) {',
		'    float gate = step(float(i), u_octaves - 0.5);',
		'    sum += valueNoise(p) * amp * gate;',
		'    norm += amp * gate;',
		'    p *= 2.03;',
		'    amp *= 0.5;',
		'  }',
		'  return sum / max(norm, 0.001);',
		'}',
		'',
		'void main() {',
		'  vec2 p = vTexCoord;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  vec3 drift = u_speed * u_time;',
		'  vec3 q = vec3(p * u_scale, 0.0) + u_translate + drift;',
		'  q.xy += 0.35 * vec2(valueNoise(q), valueNoise(q.yxz));',
		'  float v = fbm(q);',
		'  v = clamp(pow(max(v, 0.0), 1.0 / max(u_contrast, 0.08)), 0.0, 1.0);',
		'  v = clamp(v * u_amplitude + u_offset, 0.0, 1.0);',
		'  gl_FragColor = vec4(blendWith(vec3(v)), 1.0);',
		'}'
	].join('\n');

	const CAMERA = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform sampler2D u_video;',
		BLEND_FN,
		'',
		'void main() {',
		'  vec3 cam = texture2D(u_video, vTexCoord).rgb;',
		'  gl_FragColor = vec4(blendWith(cam), 1.0);',
		'}'
	].join('\n');

	const KALEIDOSCOPE = [
		FILTER,
		TILE_FN,
		'uniform float u_segments;',
		'uniform float u_angle;',
		'uniform float u_zoom;',
		'uniform float u_offsetX;',
		'uniform float u_offsetY;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 uv = vTexCoord - 0.5;',
		'  uv.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  uv -= vec2(u_offsetX, u_offsetY) - 0.5;',
		'  float ang = u_angle * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  uv = vec2(c * uv.x - s * uv.y, s * uv.x + c * uv.y);',
		'  float r = length(uv);',
		'  float a = atan(uv.y, uv.x);',
		'  float slices = max(u_segments, 2.0);',
		'  float ta = 3.14159265 / slices;',
		'  a = mod(a, ta * 2.0);',
		'  a = abs(a - ta);',
		'  vec2 st = vec2(cos(a), sin(a)) * r / max(u_zoom, 0.05);',
		'  st.x /= u_resolution.x / max(u_resolution.y, 1.0);',
		'  st += 0.5;',
		'  gl_FragColor = texture2D(u_input, tileUv(st, u_tile));',
		'}'
	].join('\n');

	const WARP = [
		FILTER,
		TILE_FN,
		'uniform float u_amount;',
		'uniform float u_frequency;',
		'uniform float u_speed;',
		'uniform float u_detail;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  float t = u_time * u_speed;',
		'  vec2 q = st;',
		'  q += u_amount * 0.22 * vec2(',
		'    sin(st.y * u_frequency + t),',
		'    cos(st.x * u_frequency * 0.91 - t)',
		'  );',
		'  q += u_amount * u_detail * 0.12 * vec2(',
		'    sin(q.y * u_frequency * 2.15 - t * 1.3),',
		'    cos(q.x * u_frequency * 1.87 + t * 1.1)',
		'  );',
		'  gl_FragColor = texture2D(u_input, tileUv(q, u_tile));',
		'}'
	].join('\n');

	const HSV_FN = [
		'vec3 rgb2hsv(vec3 c) {',
		'  vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);',
		'  vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));',
		'  vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));',
		'  float d = q.x - min(q.w, q.y);',
		'  float e = 1.0e-10;',
		'  return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);',
		'}',
		'',
		'vec3 hsv2rgb(vec3 c) {',
		'  vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);',
		'  vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);',
		'  return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);',
		'}'
	].join('\n');

	const LOOKUP = [
		FILTER,
		'uniform sampler2D u_lut;',
		'uniform float u_hue;',
		'uniform float u_saturation;',
		'uniform float u_exposure;',
		HSV_FN,
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float luma = dot(col, vec3(0.299, 0.587, 0.114));',
		'  vec3 mapped = texture2D(u_lut, vec2(clamp(luma, 0.0, 1.0), 0.5)).rgb;',
		'  vec3 hsv = rgb2hsv(mapped);',
		'  hsv.x = fract(hsv.x + u_hue / 360.0);',
		'  hsv.y = clamp(hsv.y * u_saturation, 0.0, 1.0);',
		'  mapped = hsv2rgb(hsv) * u_exposure;',
		'  gl_FragColor = vec4(clamp(mapped, 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const HSV = [
		FILTER,
		'uniform float u_hue;',
		'uniform float u_saturation;',
		'uniform float u_value;',
		HSV_FN,
		'',
		'void main() {',
		'  vec3 hsv = rgb2hsv(src().rgb);',
		'  hsv.x = fract(hsv.x + u_hue / 360.0);',
		'  hsv.y = clamp(hsv.y * u_saturation, 0.0, 1.0);',
		'  hsv.z = clamp(hsv.z * u_value, 0.0, 1.0);',
		'  gl_FragColor = vec4(hsv2rgb(hsv), 1.0);',
		'}'
	].join('\n');

	const LEVELS = [
		FILTER,
		'uniform float u_inBlack;',
		'uniform float u_inWhite;',
		'uniform float u_gamma;',
		'uniform float u_outBlack;',
		'uniform float u_outWhite;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float span = max(u_inWhite - u_inBlack, 1.0e-4);',
		'  vec3 x = clamp((col - u_inBlack) / span, 0.0, 1.0);',
		'  x = pow(max(x, 0.0), vec3(1.0 / max(u_gamma, 0.08)));',
		'  col = mix(vec3(u_outBlack), vec3(u_outWhite), x);',
		'  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const CONTRAST = [
		FILTER,
		'uniform float u_contrast;',
		'uniform float u_brightness;',
		'uniform float u_pivot;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  col = (col - u_pivot) * u_contrast + u_pivot + u_brightness;',
		'  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const RAMP = [
		FILTER,
		'uniform sampler2D u_lut;',
		'uniform float u_phase;',
		'uniform float u_period;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float luma = dot(col, vec3(0.299, 0.587, 0.114));',
		'  float t = luma * u_period + u_phase;',
		'  t = t - floor(t);',
		'  float texel = 0.5 / 256.0;',
		'  vec3 mapped = texture2D(u_lut, vec2(clamp(t, texel, 1.0 - texel), 0.5)).rgb;',
		'  gl_FragColor = vec4(mapped, 1.0);',
		'}'
	].join('\n');

	const BLOOM_BRIGHT = [
		FILTER,
		'uniform float u_threshold;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  float luma = dot(col, vec3(0.2126, 0.7152, 0.0722));',
		'  float knee = max(u_threshold * 0.5, 0.001);',
		'  float soft = luma - u_threshold + knee;',
		'  soft = clamp(soft, 0.0, 2.0 * knee);',
		'  soft = (soft * soft) / (4.0 * knee);',
		'  float contrib = max(soft, luma - u_threshold) / max(luma, 1.0e-4);',
		'  gl_FragColor = vec4(col * contrib, 1.0);',
		'}'
	].join('\n');

	const BLOOM_DOWN = [
		FILTER,
		'uniform vec2 u_texel;',
		'uniform float u_offset;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 halfpixel = u_texel * u_offset;',
		'  vec3 sum = texture2D(u_input, st).rgb * 4.0;',
		'  sum += texture2D(u_input, st - halfpixel).rgb;',
		'  sum += texture2D(u_input, st + halfpixel).rgb;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x, -halfpixel.y)).rgb;',
		'  sum += texture2D(u_input, st - vec2(halfpixel.x, -halfpixel.y)).rgb;',
		'  gl_FragColor = vec4(sum / 8.0, 1.0);',
		'}'
	].join('\n');

	const BLOOM_UP = [
		FILTER,
		'uniform vec2 u_texel;',
		'uniform float u_offset;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 halfpixel = u_texel * u_offset;',
		'  vec3 sum = texture2D(u_input, st + vec2(-halfpixel.x * 2.0, 0.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(-halfpixel.x, halfpixel.y)).rgb * 2.0;',
		'  sum += texture2D(u_input, st + vec2(0.0, halfpixel.y * 2.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x, halfpixel.y)).rgb * 2.0;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x * 2.0, 0.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(halfpixel.x, -halfpixel.y)).rgb * 2.0;',
		'  sum += texture2D(u_input, st + vec2(0.0, -halfpixel.y * 2.0)).rgb;',
		'  sum += texture2D(u_input, st + vec2(-halfpixel.x, -halfpixel.y)).rgb * 2.0;',
		'  gl_FragColor = vec4(sum / 12.0, 1.0);',
		'}'
	].join('\n');

	const BLOOM_COMP = [
		FILTER,
		'uniform sampler2D u_bloom;',
		'uniform float u_intensity;',
		'',
		'void main() {',
		'  vec3 col = src().rgb;',
		'  vec3 glow = texture2D(u_bloom, uv()).rgb * u_intensity;',
		'  vec3 add = col + glow;',
		'  vec3 screen = vec3(1.0) - (vec3(1.0) - col) * (vec3(1.0) - glow);',
		'  gl_FragColor = vec4(mix(add, screen, 0.55), 1.0);',
		'}'
	].join('\n');

	const EDGE = [
		FILTER,
		'uniform float u_threshold;',
		'uniform float u_intensity;',
		'uniform float u_radius;',
		'uniform float u_mix;',
		'uniform float u_invert;',
		'',
		'float lumaAt(vec2 st) {',
		'  vec3 col = texture2D(u_input, clamp(st, 0.0, 1.0)).rgb;',
		'  return dot(col, vec3(0.299, 0.587, 0.114));',
		'}',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 texel = (1.0 / max(u_resolution, vec2(1.0))) * max(u_radius, 0.15);',
		'  float tl = lumaAt(st + vec2(-texel.x, -texel.y));',
		'  float t  = lumaAt(st + vec2(0.0, -texel.y));',
		'  float tr = lumaAt(st + vec2(texel.x, -texel.y));',
		'  float l  = lumaAt(st + vec2(-texel.x, 0.0));',
		'  float r  = lumaAt(st + vec2(texel.x, 0.0));',
		'  float bl = lumaAt(st + vec2(-texel.x, texel.y));',
		'  float b  = lumaAt(st + vec2(0.0, texel.y));',
		'  float br = lumaAt(st + vec2(texel.x, texel.y));',
		'  float gx = -tl + tr - 2.0 * l + 2.0 * r - bl + br;',
		'  float gy = -tl - 2.0 * t - tr + bl + 2.0 * b + br;',
		'  float mag = length(vec2(gx, gy));',
		'  float edge = clamp((mag - u_threshold) * u_intensity, 0.0, 1.0);',
		'  edge = mix(edge, 1.0 - edge, clamp(u_invert, 0.0, 1.0));',
		'  vec3 srcCol = src().rgb;',
		'  gl_FragColor = vec4(mix(srcCol, vec3(edge), clamp(u_mix, 0.0, 1.0)), 1.0);',
		'}'
	].join('\n');

	const COPY = [
		FILTER,
		'uniform float u_gain;',
		'',
		'void main() {',
		'  gl_FragColor = vec4(src().rgb * u_gain, 1.0);',
		'}'
	].join('\n');

	const MASK_SHAPE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform sampler2D u_input;',
		'uniform float u_hasPrev;',
		'uniform float u_shape;',
		'uniform vec2 u_center;',
		'uniform vec2 u_size;',
		'uniform float u_feather;',
		'uniform float u_invert;',
		'',
		'float cover() {',
		'  vec2 px = vTexCoord * u_resolution;',
		'  vec2 c = u_center * u_resolution;',
		'  float m = min(u_resolution.x, u_resolution.y);',
		'  float feather = max(u_feather * m, 1.0);',
		'  float d;',
		'  if (u_shape < 0.5) {',
		'    vec2 halfPx = max(u_size * 0.5 * u_resolution, vec2(1.0));',
		'    vec2 q = abs(px - c) - halfPx;',
		'    d = length(max(q, 0.0)) + min(max(q.x, q.y), 0.0);',
		'  } else {',
		'    float r = max(u_size.x * m, 1.0);',
		'    d = length(px - c) - r;',
		'  }',
		'  return 1.0 - smoothstep(-feather, feather, d);',
		'}',
		'',
		'void main() {',
		'  float prev = u_hasPrev > 0.5 ? texture2D(u_input, vTexCoord).r : 0.0;',
		'  float shape = cover();',
		'  float next = u_invert > 0.5 ? prev * (1.0 - shape) : max(prev, shape);',
		'  gl_FragColor = vec4(next, next, next, 1.0);',
		'}'
	].join('\n');

	const CORNER_PIN = [
		FILTER,
		'uniform sampler2D u_mask;',
		'uniform float u_hasMask;',
		'uniform float u_maskInvert;',
		'uniform vec3 u_h0;',
		'uniform vec3 u_h1;',
		'uniform vec3 u_h2;',
		'',
		'void main() {',
		'  vec3 q = vec3(uv(), 1.0);',
		'  vec3 hp = vec3(dot(u_h0, q), dot(u_h1, q), dot(u_h2, q));',
		'  if (abs(hp.z) < 1.0e-6) {',
		'    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);',
		'    return;',
		'  }',
		'  vec2 st = hp.xy / hp.z;',
		'  if (st.x < 0.0 || st.x > 1.0 || st.y < 0.0 || st.y > 1.0) {',
		'    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);',
		'    return;',
		'  }',
		'  vec3 col = texture2D(u_input, st).rgb;',
		'  float m = 1.0;',
		'  if (u_hasMask > 0.5) {',
		'    m = texture2D(u_mask, st).r;',
		'    m = mix(m, 1.0 - m, clamp(u_maskInvert, 0.0, 1.0));',
		'  }',
		'  gl_FragColor = vec4(col * m, 1.0);',
		'}'
	].join('\n');

	const TEST_CARD = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'',
		'void main() {',
		'  vec2 uv = vTexCoord;',
		'  vec2 p = uv * 2.0 - 1.0;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  vec2 cells = uv * vec2(16.0, 9.0);',
		'  vec2 g = abs(fract(cells) - 0.5);',
		'  float line = 1.0 - smoothstep(0.0, 0.06, min(g.x, g.y));',
		'  float cross = step(abs(uv.x - 0.5), 0.0015) + step(abs(uv.y - 0.5), 0.0015);',
		'  float r = length(p);',
		'  float ring = 0.0;',
		'  ring += 1.0 - smoothstep(0.0, 0.012, abs(r - 0.22));',
		'  ring += 1.0 - smoothstep(0.0, 0.012, abs(r - 0.44));',
		'  ring += 1.0 - smoothstep(0.0, 0.012, abs(r - 0.66));',
		'  float frame = step(min(min(uv.x, 1.0 - uv.x), min(uv.y, 1.0 - uv.y)), 0.018);',
		'  vec3 col = vec3(0.07);',
		'  col += vec3(0.42) * line;',
		'  col += vec3(0.95) * clamp(cross, 0.0, 1.0);',
		'  col += vec3(0.85) * clamp(ring, 0.0, 1.0);',
		'  col = mix(col, vec3(1.0), frame);',
		'  vec2 c = uv;',
		'  if (c.x < 0.08 && c.y < 0.08) col = vec3(0.85, 0.18, 0.16);',
		'  if (c.x > 0.92 && c.y < 0.08) col = vec3(0.18, 0.72, 0.28);',
		'  if (c.x > 0.92 && c.y > 0.92) col = vec3(0.2, 0.45, 0.95);',
		'  if (c.x < 0.08 && c.y > 0.92) col = vec3(0.95, 0.82, 0.18);',
		'  gl_FragColor = vec4(col, 1.0);',
		'}'
	].join('\n');

	const SHAPE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_kind;',
		'uniform vec2 u_center;',
		'uniform vec2 u_size;',
		'uniform float u_sides;',
		'uniform float u_rotation;',
		'uniform float u_feather;',
		'uniform vec3 u_color;',
		BLEND_FN,
		'',
		'float sdBox(vec2 p, vec2 b) {',
		'  vec2 q = abs(p) - b;',
		'  return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0);',
		'}',
		'',
		'float sdPolygon(vec2 p, float n, float radius) {',
		'  float ang = 3.14159265 / max(n, 3.0);',
		'  float a = atan(p.x, p.y);',
		'  float d = cos(floor(0.5 + a / ang) * ang - a) * length(p);',
		'  return d - radius * cos(ang);',
		'}',
		'',
		'void main() {',
		'  vec2 px = vTexCoord * u_resolution;',
		'  vec2 c = u_center * u_resolution;',
		'  float m = min(u_resolution.x, u_resolution.y);',
		'  float feather = max(u_feather * m, 1.0);',
		'  vec2 p = px - c;',
		'  float ang = u_rotation * 0.017453292;',
		'  float cs = cos(ang);',
		'  float sn = sin(ang);',
		'  p = vec2(cs * p.x - sn * p.y, sn * p.x + cs * p.y);',
		'  float d;',
		'  if (u_kind < 0.5) {',
		'    d = length(p) - max(u_size.x * m, 1.0);',
		'  } else if (u_kind < 1.5) {',
		'    vec2 halfPx = max(u_size * 0.5 * u_resolution, vec2(1.0));',
		'    d = sdBox(p, halfPx);',
		'  } else {',
		'    d = sdPolygon(p, max(u_sides, 3.0), max(u_size.x * m, 1.0));',
		'  }',
		'  float v = 1.0 - smoothstep(-feather, feather, d);',
		'  gl_FragColor = vec4(blendWith(u_color * v), 1.0);',
		'}'
	].join('\n');

	const GRADIENT = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_kind;',
		'uniform float u_angle;',
		'uniform float u_position;',
		'uniform float u_spread;',
		'uniform vec3 u_colorA;',
		'uniform vec3 u_colorB;',
		BLEND_FN,
		'',
		'void main() {',
		'  vec2 p = vTexCoord - 0.5;',
		'  p.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_angle * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  vec2 q = vec2(c * p.x - s * p.y, s * p.x + c * p.y);',
		'  float t;',
		'  if (u_kind < 0.5) {',
		'    t = q.x * 0.5 + 0.5;',
		'  } else if (u_kind < 1.5) {',
		'    t = length(q) / 0.75;',
		'  } else {',
		'    t = atan(q.y, q.x) / 6.2831853 + 0.5;',
		'  }',
		'  float span = max(u_spread, 0.02);',
		'  t = (t - u_position) / span + 0.5;',
		'  t = clamp(t, 0.0, 1.0);',
		'  gl_FragColor = vec4(blendWith(mix(u_colorA, u_colorB, t)), 1.0);',
		'}'
	].join('\n');

	const DISPLACE = [
		FILTER,
		TILE_FN,
		'uniform float u_amount;',
		'uniform float u_angle;',
		'uniform float u_center;',
		'uniform float u_mode;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec3 map = texture2D(u_input, st).rgb;',
		'  vec2 delta;',
		'  if (u_mode > 0.5) {',
		'    delta = (map.rg - vec2(u_center)) * u_amount;',
		'  } else {',
		'    float luma = dot(map, vec3(0.299, 0.587, 0.114));',
		'    float ang = u_angle * 0.017453292;',
		'    delta = vec2(cos(ang), sin(ang)) * (luma - u_center) * u_amount;',
		'  }',
		'  gl_FragColor = texture2D(u_input, tileUv(st + delta, u_tile));',
		'}'
	].join('\n');

	const BLUR = [
		FILTER,
		'uniform vec2 u_axis;',
		'uniform float u_radius;',
		'uniform float u_mix;',
		'uniform float u_final;',
		'uniform sampler2D u_dry;',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  vec2 px = u_axis * u_radius / max(u_resolution, vec2(1.0));',
		'  vec3 sum = texture2D(u_input, st).rgb * 0.227027;',
		'  sum += texture2D(u_input, st + px * 1.384615).rgb * 0.316216;',
		'  sum += texture2D(u_input, st - px * 1.384615).rgb * 0.316216;',
		'  sum += texture2D(u_input, st + px * 3.230769).rgb * 0.070270;',
		'  sum += texture2D(u_input, st - px * 3.230769).rgb * 0.070270;',
		'  if (u_final > 0.5) {',
		'    vec3 dry = texture2D(u_dry, st).rgb;',
		'    sum = mix(dry, sum, clamp(u_mix, 0.0, 1.0));',
		'  }',
		'  gl_FragColor = vec4(sum, 1.0);',
		'}'
	].join('\n');

	const FEEDBACK = [
		FILTER,
		TILE_FN,
		'uniform sampler2D u_feedback;',
		'uniform float u_amount;',
		'uniform float u_decay;',
		'uniform float u_scale;',
		'uniform float u_rotate;',
		'uniform vec2 u_offset;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv() - 0.5;',
		'  st.x *= u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_rotate * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  st = vec2(c * st.x - s * st.y, s * st.x + c * st.y);',
		'  st *= max(u_scale, 0.2);',
		'  st.x /= u_resolution.x / max(u_resolution.y, 1.0);',
		'  st += 0.5 + u_offset;',
		'  vec3 trail = texture2D(u_feedback, tileUv(st, u_tile)).rgb * clamp(u_decay, 0.0, 1.0);',
		'  vec3 src = src().rgb;',
		'  gl_FragColor = vec4(clamp(mix(src, src + trail, clamp(u_amount, 0.0, 1.0)), 0.0, 1.0), 1.0);',
		'}'
	].join('\n');

	const GLITCH = [
		FILTER,
		TILE_FN,
		'uniform float u_amount;',
		'uniform float u_speed;',
		'uniform float u_narrowness;',
		'uniform float u_blockiness;',
		'uniform float u_sparsity;',
		'uniform float u_chroma;',
		'uniform float u_angle;',
		'uniform float u_tile;',
		'',
		'float satf(float t) {',
		'  return clamp(t, 0.0, 1.0);',
		'}',
		'',
		'float remap01(float t, float a, float b) {',
		'  return satf((t - a) / max(b - a, 1.0e-4));',
		'}',
		'',
		'float linterp(float t) {',
		'  return satf(1.0 - abs(2.0 * t - 1.0));',
		'}',
		'',
		'float qstep(float x, float levels) {',
		'  float n = max(levels, 1.0);',
		'  return floor(x * n) / n;',
		'}',
		'',
		'vec2 qstep2(vec2 x, float levels) {',
		'  float n = max(levels, 1.0);',
		'  return floor(x * n) / n;',
		'}',
		'',
		'float hash21(vec2 n) {',
		'  return fract(sin(dot(n, vec2(12.9898, 78.233))) * 43758.5453);',
		'}',
		'',
		'float glitchRand(vec2 p, float t) {',
		'  vec2 k = vec2(12.9898, 78.233) * (t + 1.17);',
		'  return fract(sin(dot(p, k)) * 43758.5453);',
		'}',
		'',
		'float glitchNoise(vec2 st, float blockiness, float t) {',
		'  vec2 lv = fract(st);',
		'  vec2 id = floor(st);',
		'  float n1 = glitchRand(id, t);',
		'  float n2 = glitchRand(id + vec2(1.0, 0.0), t);',
		'  float n3 = glitchRand(id + vec2(0.0, 1.0), t);',
		'  float n4 = glitchRand(id + vec2(1.0, 1.0), t);',
		'  vec2 u = smoothstep(0.0, 1.0 + blockiness, lv);',
		'  return mix(mix(n1, n2, u.x), mix(n3, n4, u.x), u.y);',
		'}',
		'',
		'float glitchFbm(vec2 st, float blockiness, float complexity, float t) {',
		'  float val = 0.0;',
		'  float amp = 0.5;',
		'  for (int i = 0; i < 4; i++) {',
		'    val += amp * glitchNoise(st, blockiness, t);',
		'    amp *= 0.5;',
		'    st *= complexity;',
		'  }',
		'  return val;',
		'}',
		'',
		'vec3 spectrumOffset(float t) {',
		'  float lo = step(t, 0.5);',
		'  float hi = 1.0 - lo;',
		'  float w = linterp(remap01(t, 0.1666667, 0.8333333));',
		'  vec3 ret = vec3(lo, 1.0, hi) * vec3(1.0 - w, w, 1.0 - w);',
		'  return pow(max(ret, vec3(0.0)), vec3(0.45454545));',
		'}',
		'',
		'void main() {',
		'  vec2 st = uv();',
		'  float amount = satf(u_amount);',
		'  if (amount < 0.0001) {',
		'    gl_FragColor = texture2D(u_input, st);',
		'    return;',
		'  }',
		'  float aspect = u_resolution.x / max(u_resolution.y, 1.0);',
		'  float ang = u_angle * 0.017453292;',
		'  float cs = cos(ang);',
		'  float sn = sin(ang);',
		'  vec2 dir = vec2(cs, sn);',
		'  vec2 perp = vec2(-sn, cs);',
		'  vec2 q = st - 0.5;',
		'  q.x *= aspect;',
		'  q = vec2(cs * q.x + sn * q.y, -sn * q.x + cs * q.y);',
		'  q.x /= aspect;',
		'  vec2 local = q + 0.5;',
		'  float hz = max(u_speed, 0.0) * 4.0;',
		'  float seed = hz < 1.0e-4 ? 0.0 : floor(u_time * hz);',
		'  float gtime = seed;',
		'  float tick = seed * 0.13;',
		'  float gnm = amount;',
		'  float rnd0 = hash21(qstep2(vec2(gtime, gtime), 6.0));',
		'  float r0 = satf((1.0 - gnm) * 0.7 + rnd0);',
		'  float strips = mix(6.0, 72.0, satf((u_narrowness - 0.5) / 15.5));',
		'  float rnd1 = hash21(vec2(qstep(local.x, 10.0 * r0), gtime));',
		'  float r1 = 0.5 - 0.5 * gnm + rnd1;',
		'  r1 = 1.0 - max(0.0, min(r1, 0.9999999));',
		'  float rnd2 = hash21(vec2(qstep(local.y, strips * r1), gtime));',
		'  float r2 = satf(rnd2);',
		'  float rnd3 = hash21(vec2(qstep(local.y, 10.0 * r0), gtime));',
		'  float r3 = (1.0 - satf(rnd3 + 0.8)) - 0.1;',
		'  float pxrnd = hash21(local + gtime);',
		'  float rare = satf((u_sparsity - 1.0) / 15.0);',
		'  float cut = mix(0.02, 0.84, rare);',
		'  float live = smoothstep(cut, min(cut + mix(0.38, 0.07, rare), 1.0), r2);',
		'  float stripOfs = 0.05 * r2 * gnm * (rnd0 > 0.5 ? 1.0 : -1.0);',
		'  stripOfs += 0.5 * pxrnd * stripOfs;',
		'  vec2 domain = vec2(local.x * aspect * 0.45 + 5.13, local.y * max(u_narrowness, 0.5) + 3.71);',
		'  float n = clamp(glitchFbm(domain, u_blockiness, max(u_narrowness, 0.5), tick), 0.0, 1.0);',
		'  live *= mix(1.0, pow(max(n, 1.0e-6), mix(1.0, 4.0, rare)), rare * 0.7);',
		'  float ofs = stripOfs * live;',
		'  ofs += (n * 2.0 - 1.0) * amount * 0.1 * live;',
		'  vec2 base = st + perp * (0.1 * r3 * gnm * live);',
		'  float smear = max(u_chroma, 0.0);',
		'  vec3 col;',
		'  if (smear < 0.01) {',
		'    col = texture2D(u_input, tileUv(base + dir * ofs, u_tile)).rgb;',
		'  } else {',
		'    vec3 sum = vec3(0.0);',
		'    vec3 wsum = vec3(0.0);',
		'    for (int i = 0; i < 8; i++) {',
		'      float t = float(i) * 0.125;',
		'      vec3 w = mix(vec3(1.0), spectrumOffset(t), satf(smear));',
		'      vec2 suv = base + dir * (ofs * t * smear);',
		'      sum += texture2D(u_input, tileUv(suv, u_tile)).rgb * w;',
		'      wsum += w;',
		'    }',
		'    col = sum / max(wsum, vec3(1.0e-4));',
		'  }',
		'  gl_FragColor = vec4(col, 1.0);',
		'}'
	].join('\n');

	const TAPE = [
		'varying vec2 vTexCoord;',
		'uniform vec2 u_resolution;',
		'uniform float u_time;',
		'uniform float u_speed;',
		'uniform float u_lines;',
		'uniform float u_threshold;',
		'uniform float u_grain;',
		'uniform float u_amount;',
		BLEND_FN,
		'',
		'vec4 hash42(vec2 p) {',
		'  vec4 p4 = fract(vec4(p.xyxy) * vec4(443.8975, 397.2973, 491.1871, 470.7827));',
		'  p4 += dot(p4.wzxy, p4 + 19.19);',
		'  return fract(vec4(p4.x * p4.y, p4.x * p4.z, p4.y * p4.w, p4.x * p4.w));',
		'}',
		'',
		'float hash1(float n) {',
		'  return fract(sin(n) * 43758.5453123);',
		'}',
		'',
		'float iqNoise(vec3 x) {',
		'  vec3 p = floor(x);',
		'  vec3 f = fract(x);',
		'  f = f * f * (3.0 - 2.0 * f);',
		'  float n = p.x + p.y * 57.0 + 113.0 * p.z;',
		'  return mix(',
		'    mix(',
		'      mix(hash1(n + 0.0), hash1(n + 1.0), f.x),',
		'      mix(hash1(n + 57.0), hash1(n + 58.0), f.x),',
		'      f.y',
		'    ),',
		'    mix(',
		'      mix(hash1(n + 113.0), hash1(n + 114.0), f.x),',
		'      mix(hash1(n + 170.0), hash1(n + 171.0), f.x),',
		'      f.y',
		'    ),',
		'    f.z',
		'  );',
		'}',
		'',
		'float tapeNoise(vec2 p, float t) {',
		'  float y = p.y;',
		'  float s = t * u_speed;',
		'  float v = iqNoise(vec3(y * 0.01 + s, 1.0, 1.0));',
		'  v *= iqNoise(vec3(y * 0.011 + 1000.0 + s, 1.0, 1.0));',
		'  v *= iqNoise(vec3(y * 0.51 + 421.0 + s, 1.0, 1.0));',
		'  float cell = hash42(vec2(p.x + t * 0.01, p.y)).x + 0.3;',
		'  v *= mix(1.0, cell, clamp(u_grain, 0.0, 2.0));',
		'  v = v + 0.3;',
		'  v *= step(u_threshold, v);',
		'  return v * u_amount;',
		'}',
		'',
		'void main() {',
		'  vec2 frag = vTexCoord * u_resolution;',
		'  float oneY = u_resolution.y / max(u_lines, 1.0);',
		'  vec2 p = floor(frag / oneY) * oneY;',
		'  float col = tapeNoise(p, u_time);',
		'  gl_FragColor = vec4(blendWith(vec3(col)), 1.0);',
		'}'
	].join('\n');

	const TRANSFORM = [
		FILTER,
		TILE_FN,
		'uniform vec2 u_translate;',
		'uniform float u_rotate;',
		'uniform vec2 u_scale;',
		'uniform float u_tile;',
		'',
		'void main() {',
		'  vec2 st = uv() - 0.5;',
		'  st -= u_translate;',
		'  float aspect = u_resolution.x / max(u_resolution.y, 1.0);',
		'  st.x *= aspect;',
		'  float ang = -u_rotate * 0.017453292;',
		'  float c = cos(ang);',
		'  float s = sin(ang);',
		'  st = vec2(c * st.x - s * st.y, s * st.x + c * st.y);',
		'  vec2 sc = max(u_scale, vec2(0.001));',
		'  st /= sc;',
		'  st.x /= aspect;',
		'  st += 0.5;',
		'  gl_FragColor = texture2D(u_input, tileUv(st, u_tile));',
		'}'
	].join('\n');

	root.SYNTH_SHADERS = {
		vert: VERT,
		lines: LINES,
		noise: NOISE,
		camera: CAMERA,
		warp: WARP,
		lookup: LOOKUP,
		ramp: RAMP,
		hsv: HSV,
		levels: LEVELS,
		contrast: CONTRAST,
		kaleidoscope: KALEIDOSCOPE,
		bloomBright: BLOOM_BRIGHT,
		bloomDown: BLOOM_DOWN,
		bloomUp: BLOOM_UP,
		bloomComp: BLOOM_COMP,
		edge: EDGE,
		copy: COPY,
		maskShape: MASK_SHAPE,
		cornerPin: CORNER_PIN,
		testCard: TEST_CARD,
		shape: SHAPE,
		gradient: GRADIENT,
		displace: DISPLACE,
		blur: BLUR,
		feedback: FEEDBACK,
		transform: TRANSFORM,
		glitch: GLITCH,
		tape: TAPE
	};
})(window);
