# Generated by Django 3.0.8 on 2020-08-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0002_remove_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=150),
        ),
    ]
