# Generated by Django 3.0.8 on 2020-08-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
    ]
