# Generated by Django 3.0.8 on 2020-09-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0007_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('arte_computacional', 'Arte Computacional'), ('instalacoes', 'Instalações'), ('performances', 'Performances'), ('educacao', 'Educação'), ('dancatech', 'Dança e Tecnologia')], default='arte_computacional', max_length=100),
        ),
    ]
