# Generated by Django 3.0.8 on 2020-09-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0011_remove_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Arte Computacional', 'arte_computacional'), ('Instalações', 'instalacoes'), ('Performances', 'performances'), ('Educação', 'educacao'), ('Dança', 'dancatech')], default='arte_computacional', max_length=100),
        ),
    ]
