# Generated by Django 3.0.8 on 2020-09-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0012_auto_20200905_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('arte_computacional', 'Arte Computacional'), ('instalacoes', 'Instalações'), ('performances', 'Performances'), ('educacao', 'Educação'), ('dancatech', 'Dança')], default='arte_computacional', max_length=100),
        ),
    ]
