# Generated by Django 3.0.8 on 2020-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0015_auto_20200910_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('arte_computacional', 'Computational Art'), ('instalacoes', 'Installations'), ('performances', 'Performances'), ('educacao', 'Education'), ('dancatech', 'Dance')], default='arte_computacional', max_length=150),
        ),
    ]
