# Generated by Django 3.0.8 on 2020-09-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0018_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(default='', max_length=150),
        ),
    ]
