# Generated by Django 3.0.8 on 2020-09-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0006_auto_20200831_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
