# Generated by Django 3.0.8 on 2020-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0009_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
    ]
