# Generated by Django 3.0.8 on 2020-09-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0010_auto_20200902_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
