# Generated by Django 3.0.8 on 2020-09-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0017_auto_20200912_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(default='')),
                ('host', models.CharField(choices=[('vimeo', 'Vimeo'), ('youtube', 'Youtube')], default='youtube', max_length=10)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miccoliPortfolio.Project')),
            ],
        ),
    ]
