# Generated by Django 3.0.8 on 2020-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miccoliPortfolio', '0019_auto_20200913_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='credit',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
